### ISSUE TITLE
ruby 2.5.3p105 undefined method `alias_method_chain' for ActiveResource::Base:Class

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [PipelineDeals/pipelinedeals_api#16]
I can't make it work somehow to start even the console, after including this gem in my Gemfile.

Rails 5.2.2

```shell
/Users/user/.rvm/gems/ruby-2.5.3/gems/activeresource-4.0.0.beta1/lib/active_resource/validations.rb:103:in `block in <module:Validations>': undefined method `alias_method_chain' for ActiveResource::Base:Class
Did you mean?  alias_method (NoMethodError)
  from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.3/lib/active_support/concern.rb:122:in `class_eval'
  from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.3/lib/active_support/concern.rb:122:in `append_features'
  from /Users/user/.rvm/gems/ruby-2.5.3/gems/activeresource-4.0.0.beta1/lib/active_resource/base.rb:1557:in `include'
  from /Users/user/.rvm/gems/ruby-2.5.3/gems/activeresource-4.0.0.beta1/lib/active_resource/base.rb:1557:in `<class:Base>'
  from /Users/user/.rvm/gems/ruby-2.5.3/gems/activeresource-4.0.0.beta1/lib/active_resource/base.rb:1553:in `<module:ActiveResource>'
  from /Users/user/.rvm/gems/ruby-2.5.3/gems/activeresource-4.0.0.beta1/lib/active_resource/base.rb:22:in `<top (required)>'
  from /Users/user/.rvm/gems/ruby-2.5.3/gems/pipeline_deals-0.1.0/lib/pipeline_deals/resource.rb:2:in `require'
  from /Users/user/.rvm/gems/ruby-2.5.3/gems/pipeline_deals-0.1.0/lib/pipeline_deals/resource.rb:2:in `<module:PipelineDeals>'
  from /Users/user/.rvm/gems/ruby-2.5.3/gems/pipeline_deals-0.1.0/lib/pipeline_deals/resource.rb:1:in `<top (required)>'
  from /Users/user/.rvm/gems/ruby-2.5.3/gems/pipeline_deals-0.1.0/lib/pipeline_deals/resources.rb:2:in `require_relative'
  from /Users/user/.rvm/gems/ruby-2.5.3/gems/pipeline_deals-0.1.0/lib/pipeline_deals/resources.rb:2:in `<top (required)>'
  from /Users/user/.rvm/gems/ruby-2.5.3/gems/pipeline_deals-0.1.0/lib/pipeline_deals.rb:3:in `require_relative'
  from /Users/user/.rvm/gems/ruby-2.5.3/gems/pipeline_deals-0.1.0/lib/pipeline_deals.rb:3:in `<top (required)>'
  from /Users/user/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:81:in `require'
  from /Users/user/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:81:in `block (2 levels) in require'
  from /Users/user/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:76:in `each'
  from /Users/user/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:76:in `block in require'
  from /Users/user/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:65:in `each'
  from /Users/user/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:65:in `require'
  from /Users/user/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler.rb:114:in `require'
  from /Users/user/coding/event_planner/config/application.rb:7:in `<top (required)>'
  from /Users/user/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application.rb:92:in `require'
  from /Users/user/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application.rb:92:in `preload'
  from /Users/user/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
  from /Users/user/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
  from /Users/user/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
  from /Users/user/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
  from /Users/user/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
  from /Users/user/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  from /Users/user/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

**Comment by h0jeZvgoxFepBQ2C** [comment]
@dylanegan Any thoughts about this?

**Comment by dylanegan** [comment]
@h0jeZvgoxFepBQ2C I no longer actively work on this gem. @jlocke2 would you be able to assist here?

**Comment by jlocke2** [comment]
Thanks for the ping @dylanegan!  Sorry I missed this @h0jeZvgoxFepBQ2C!

Can you try installing master from the github repo?
```
gem "pipeline_deals", git: "git@github.com:PipelineDeals/pipelinedeals_api"
```

This should install `0.5.0`, which we are currently running successfully on Rails 5.2.3.  If this solves the issue for you, I will work on publishing a new version to RubyGems.

Also, just any FYI, this gem is very actively maintained (hence why it has been so long since a release), but it should work as expected.  If you run into any more issues, please let me know!

**Comment by h0jeZvgoxFepBQ2C** [comment]
Hm, it works with ```master```, would be great if you could take a look at #17 too :) On the github release tab it still shows 0.4.0?

**Comment by jlocke2** [comment]
@h0jeZvgoxFepBQ2C - Great!  Yep I will work on updating the releases.  Thanks!
